[tox]
envlist = lint, py38, py39, py310, py311, py312, py313

[testenv:lint]
skip_install = true
deps = ruff
commands =
    ruff check .
    ruff format --check .

[testenv:format]
skip_install = true
deps = ruff
commands =
    ruff format .

[testenv]
deps =
    pytest>=8.2.2
    pytest-cov>=5.0.0
    fastapi>=0.111.0
    starlette>=0.37.2
commands =
    pytest --cov=vellox --cov-fail-under=90 --cov-report=term-missing {posargs}
