name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      tox-envs: ${{ steps.set-envs.outputs.tox-envs }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Get tox environments
        id: set-envs
        run: |
          ENVS=$(tox -l | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "tox-envs=$ENVS" >> $GITHUB_OUTPUT

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-env: ${{ fromJson(needs.generate-matrix.outputs.tox-envs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: "pyproject.toml"
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Test
        run: tox -e ${{ matrix.tox-env }}
        env:
          UV_PYTHON_DOWNLOADS: auto
